/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainSWM;

import decorClass.EditButton;
import decorClass.RoundedPanel;
import decorClass.TaskReal;
import java.awt.*;
import javaant.StudyWithMe_P;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class AllJFrame extends javax.swing.JFrame {
    int round = 0;
    int numRow = 1;
    int numCol = 2;
    /**
     * Creates new form NewJFrame
     */
    public AllJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftP = new javax.swing.JPanel();
        timerPanel = new javax.swing.JPanel();
        timepanel = new decorClass.RoundedPanel();
        todoPanel = new javax.swing.JPanel();
        todoScroll = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        taskLabel = new javax.swing.JLabel();
        rightP = new javax.swing.JPanel();
        upperP = new javax.swing.JPanel();
        Calendar = new RoundedPanel(50, 50);
        CalendarRoundPanel = new decorClass.RoundedPanel();
        StudyWithMe_P swm = new StudyWithMe_P();
        swm_panel = new RoundedPanel(50, 50);
        SearchTool = new RoundedPanel(50, 50);
        searchPanel = new decorClass.RoundedPanel();
        searchButton = new decorClass.RoundedButton();
        lowerP3 = new javax.swing.JPanel();
        noteScroll = new javax.swing.JScrollPane();
        noteDisplay = new javax.swing.JPanel();
        noteEditPanel = new decorClass.RoundedPanel();
        addButton = new decorClass.CircleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(197, 230, 196));

        leftP.setBackground(new java.awt.Color(255, 255, 255));
        leftP.setForeground(new java.awt.Color(255, 255, 255));

        timerPanel.setBackground(new java.awt.Color(235, 212, 235));

        timepanel.setBackground(new java.awt.Color(237, 217, 241));

        javax.swing.GroupLayout timepanelLayout = new javax.swing.GroupLayout(timepanel);
        timepanel.setLayout(timepanelLayout);
        timepanelLayout.setHorizontalGroup(
            timepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        timepanelLayout.setVerticalGroup(
            timepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout timerPanelLayout = new javax.swing.GroupLayout(timerPanel);
        timerPanel.setLayout(timerPanelLayout);
        timerPanelLayout.setHorizontalGroup(
            timerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        timerPanelLayout.setVerticalGroup(
            timerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        todoPanel.setBackground(new java.awt.Color(212, 227, 235));

        todoScroll.setBackground(new java.awt.Color(200, 66, 68));
        todoScroll.setBorder(null);

        panel.setBackground(new java.awt.Color(160, 198, 190));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        todoScroll.setViewportView(panel);

        javax.swing.GroupLayout todoPanelLayout = new javax.swing.GroupLayout(todoPanel);
        todoPanel.setLayout(todoPanelLayout);
        todoPanelLayout.setHorizontalGroup(
            todoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todoScroll)
                .addContainerGap())
        );
        todoPanelLayout.setVerticalGroup(
            todoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taskLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        taskLabel.setForeground(new java.awt.Color(0, 153, 204));
        taskLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskLabel.setText("Today's Task");

        javax.swing.GroupLayout leftPLayout = new javax.swing.GroupLayout(leftP);
        leftP.setLayout(leftPLayout);
        leftPLayout.setHorizontalGroup(
            leftPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftPLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(taskLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
            .addComponent(todoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPLayout.setVerticalGroup(
            leftPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(taskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(todoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightP.setBackground(new java.awt.Color(255, 255, 255));
        rightP.setForeground(new java.awt.Color(255, 255, 255));

        upperP.setBackground(new java.awt.Color(211, 235, 221));

        Calendar.setBackground(null);

        CalendarRoundPanel.setBackground(new java.awt.Color(198, 198, 198));

        javax.swing.GroupLayout CalendarRoundPanelLayout = new javax.swing.GroupLayout(CalendarRoundPanel);
        CalendarRoundPanel.setLayout(CalendarRoundPanelLayout);
        CalendarRoundPanelLayout.setHorizontalGroup(
            CalendarRoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CalendarRoundPanelLayout.setVerticalGroup(
            CalendarRoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CalendarLayout = new javax.swing.GroupLayout(Calendar);
        Calendar.setLayout(CalendarLayout);
        CalendarLayout.setHorizontalGroup(
            CalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalendarLayout.createSequentialGroup()
                .addComponent(CalendarRoundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        CalendarLayout.setVerticalGroup(
            CalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalendarRoundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        swm_panel.add(swm);
        swm_panel.setBackground(new java.awt.Color(255, 255, 255));

        SearchTool.setBackground(null);

        searchPanel.setBackground(new java.awt.Color(198, 198, 198));

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        searchButton.setText("roundedButton1");

        javax.swing.GroupLayout SearchToolLayout = new javax.swing.GroupLayout(SearchTool);
        SearchTool.setLayout(SearchToolLayout);
        SearchToolLayout.setHorizontalGroup(
            SearchToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchToolLayout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        SearchToolLayout.setVerticalGroup(
            SearchToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchToolLayout.createSequentialGroup()
                .addGroup(SearchToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchToolLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout upperPLayout = new javax.swing.GroupLayout(upperP);
        upperP.setLayout(upperPLayout);
        upperPLayout.setHorizontalGroup(
            upperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(upperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(swm_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        upperPLayout.setVerticalGroup(
            upperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(upperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(swm_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(upperPLayout.createSequentialGroup()
                        .addComponent(Calendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        lowerP3.setBackground(new java.awt.Color(212, 235, 231));

        noteScroll.setBorder(null);
        noteScroll.setPreferredSize(new java.awt.Dimension(200, 4000));

        noteDisplay.setBackground(new java.awt.Color(201, 228, 200));
        noteDisplay.setLayout(new java.awt.GridLayout(1, 2));
        noteScroll.setViewportView(noteDisplay);

        noteEditPanel.setBackground(new java.awt.Color(193, 193, 193));

        javax.swing.GroupLayout noteEditPanelLayout = new javax.swing.GroupLayout(noteEditPanel);
        noteEditPanel.setLayout(noteEditPanelLayout);
        noteEditPanelLayout.setHorizontalGroup(
            noteEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        noteEditPanelLayout.setVerticalGroup(
            noteEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        addButton.setBackground(new java.awt.Color(193, 193, 193));
        addButton.setForeground(new java.awt.Color(47, 41, 41));
        addButton.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lowerP3Layout = new javax.swing.GroupLayout(lowerP3);
        lowerP3.setLayout(lowerP3Layout);
        lowerP3Layout.setHorizontalGroup(
            lowerP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerP3Layout.createSequentialGroup()
                .addComponent(noteScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lowerP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lowerP3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lowerP3Layout.createSequentialGroup()
                        .addComponent(noteEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        lowerP3Layout.setVerticalGroup(
            lowerP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerP3Layout.createSequentialGroup()
                .addGroup(lowerP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lowerP3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(noteEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(noteScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout rightPLayout = new javax.swing.GroupLayout(rightP);
        rightP.setLayout(rightPLayout);
        rightPLayout.setHorizontalGroup(
            rightPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(upperP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lowerP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        rightPLayout.setVerticalGroup(
            rightPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upperP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        round += 1;
        TaskReal newTask = new TaskReal();
        JPanel clearCol = new JPanel();
        clearCol.setBackground(null);
        panel.add(newTask);
        panel.add(clearCol);
        clearCol.add(new EditButton());
        panel.revalidate();
        panel.repaint();
        if (round >= 2) {
            numRow +=1 ;
            panel.setLayout(new GridLayout(numRow, numCol));
            System.out.println("numRow : "+numRow + ", numCol : "+numCol);
        }
        else{
            System.out.println(numRow);
        }
        this.pack();
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calendar;
    private decorClass.RoundedPanel CalendarRoundPanel;
    private javax.swing.JPanel SearchTool;
    private decorClass.CircleButton addButton;
    private javax.swing.JPanel leftP;
    private javax.swing.JPanel lowerP3;
    private javax.swing.JPanel noteDisplay;
    private decorClass.RoundedPanel noteEditPanel;
    private javax.swing.JScrollPane noteScroll;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel rightP;
    private decorClass.RoundedButton searchButton;
    private decorClass.RoundedPanel searchPanel;
    private javax.swing.JPanel swm_panel;
    private javax.swing.JLabel taskLabel;
    private decorClass.RoundedPanel timepanel;
    private javax.swing.JPanel timerPanel;
    private javax.swing.JPanel todoPanel;
    private javax.swing.JScrollPane todoScroll;
    private javax.swing.JPanel upperP;
    // End of variables declaration//GEN-END:variables
}
