/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DateInTable;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yarnisar
 */
public class Chooser extends javax.swing.JPanel {
    HashMap<String, String> map; 
    public String thisDate;
    public Chooser ch;
           
    
    /**
     * Creates new form Chooser
     */
    public Chooser() {
        initComponents();
        map = new HashMap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddButton = new decorClass.RoundedButton();
        EditButton = new decorClass.RoundedButton();
        ClearButton = new decorClass.RoundedButton();

        setBackground(new java.awt.Color(255, 255, 204));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 153));
        jDateChooser1.setForeground(new java.awt.Color(102, 255, 0));

        jTable1.setBackground(new java.awt.Color(223, 249, 216));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date"
            }
        )
        {
            public boolean isCellEditable(int row, int col){
                return false;
            }
        }
    );
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    AddButton.setBackground(new java.awt.Color(159, 190, 157));
    AddButton.setForeground(new java.awt.Color(47, 57, 41));
    AddButton.setText("Add");
    AddButton.setActionCommand("Addbutton");
    AddButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
    AddButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            AddButtonActionPerformed(evt);
        }
    });

    EditButton.setBackground(new java.awt.Color(234, 190, 179));
    EditButton.setForeground(new java.awt.Color(65, 40, 41));
    EditButton.setText("Edit");
    EditButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
    EditButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            EditButtonActionPerformed(evt);
        }
    });

    ClearButton.setBackground(new java.awt.Color(231, 231, 94));
    ClearButton.setForeground(new java.awt.Color(65, 40, 41));
    ClearButton.setText("Clear");
    ClearButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
    ClearButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ClearButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
       try{
            SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MM-yyyy");
            String thisDate = DateFormat.format(jDateChooser1.getDate()); //07/05/22544
            DefaultTableModel defaultModel = (DefaultTableModel)jTable1.getModel();
            defaultModel.addRow(new Object[]{thisDate});
//            System.out.println("fff " + "   "+  defaultModel + "   "+ thisDate +"   " + DateFormat );
            System.out.println("dateDay: " + thisDate);
            String thisDated = thisDate;
            map.put(thisDate,"1");//create hashMap
            System.out.println(map.entrySet());
//            System.out.println(thisDated);
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Date Selected");
       }
    }//GEN-LAST:event_AddButtonActionPerformed

         public String getThisDate(String thisDated){
            return thisDated;
         }
         
    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        try{
            SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MM-yyyy");
            int seectedRow = jTable1.getSelectedRow();
            String thisDate = DateFormat.format(jDateChooser1.getDate());
            DefaultTableModel defaultModel = (DefaultTableModel)jTable1.getModel();
            defaultModel.setValueAt(thisDate,seectedRow,0);
            String thisDated = thisDate;
            map.put(thisDate,"1");//create hashMap
            System.out.println(map.entrySet());
//            System.out.println(thisDated);
//            System.out.println("dateDay" + thisDate);
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Date Edit");
       }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
        try {
            
            DefaultTableModel defaultModel = (DefaultTableModel)jTable1.getModel();
            int seectedRow = jTable1.getSelectedRow();
//            seected
            Date date = new SimpleDateFormat("dd-MM-yyyy").parse((String)defaultModel.getValueAt(seectedRow,0));
            jDateChooser1.setDate(date);
//            System.out.println("dateDay" + ch.thisDate);
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Date Clear");
       }
                    
    }//GEN-LAST:event_jTable1MouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        try{
            
        DefaultTableModel defaultModel = (DefaultTableModel)jTable1.getModel();
        defaultModel.setRowCount(0);
        
        }catch (Exception ex) {
            Logger.getLogger(Chooser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ClearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public decorClass.RoundedButton AddButton;
    private decorClass.RoundedButton ClearButton;
    private decorClass.RoundedButton EditButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
