/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SUGUS
 */

import decorClass.*;
public class swing_calendar extends javax.swing.JFrame {

    /**
     * Creates new form swing_calendar
     */
    public swing_calendar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new RoundedPanel(25, 25);
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new RoundedPanel(25, 25);
        cells1 = new Cells();
        cells2 = new Cells();
        cells3 = new Cells();
        cells4 = new Cells();
        cells5 = new Cells();
        cells6 = new Cells();
        cells7 = new Cells();
        cells8 = new Cells();
        cells9 = new Cells();
        cells10 = new Cells();
        cells11 = new Cells();
        cells12 = new Cells();
        cells13 = new Cells();
        cells14 = new Cells();
        cells15 = new Cells();
        cells16 = new Cells();
        cells17 = new Cells();
        cells18 = new Cells();
        cells19 = new Cells();
        cells20 = new Cells();
        cells21 = new Cells();
        cells22 = new Cells();
        cells23 = new Cells();
        cells24 = new Cells();
        cells25 = new Cells();
        cells26 = new Cells();
        cells27 = new Cells();
        cells28 = new Cells();
        cells29 = new Cells();
        cells30 = new Cells();
        cells31 = new Cells();
        cells32 = new Cells();
        cells33 = new Cells();
        cells34 = new Cells();
        cells35 = new Cells();
        cells36 = new Cells();
        cells37 = new Cells();
        cells38 = new Cells();
        cells39 = new Cells();
        cells40 = new Cells();
        cells41 = new Cells();
        cells42 = new Cells();
        cells43 = new Cells();
        cells44 = new Cells();
        cells45 = new Cells();
        cells46 = new Cells();
        cells47 = new Cells();
        cells48 = new Cells();
        cells49 = new Cells();

        jLabel1.setBackground(new java.awt.Color(221, 221, 221));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(125, 153, 132));
        jLabel1.setText("CALENDAR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setBackground(new java.awt.Color(221, 221, 221));

        jPanel2.setBackground(new java.awt.Color(221, 221, 221));

        jLabel2.setBackground(new java.awt.Color(221, 221, 221));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(125, 153, 132));
        jLabel2.setText("Today's Task");

        jLabel3.setBackground(new java.awt.Color(221, 221, 221));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(125, 153, 132));
        jLabel3.setText("CALENDAR");

        jPanel4.setBackground(new java.awt.Color(146, 164, 182));

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jCheckBox1.setText("TASK-1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(7, 7, 1, 1));

        cells1.setText("cells1");
        cells1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells1ActionPerformed(evt);
            }
        });
        jPanel3.add(cells1);

        cells2.setText("cells2");
        jPanel3.add(cells2);

        cells3.setText("cells3");
        jPanel3.add(cells3);

        cells4.setText("cells4");
        jPanel3.add(cells4);

        cells5.setText("cells5");
        jPanel3.add(cells5);

        cells6.setText("cells1");
        cells6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells6ActionPerformed(evt);
            }
        });
        jPanel3.add(cells6);

        cells7.setText("cells1");
        cells7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells7ActionPerformed(evt);
            }
        });
        jPanel3.add(cells7);

        cells8.setText("cells1");
        cells8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells8ActionPerformed(evt);
            }
        });
        jPanel3.add(cells8);

        cells9.setText("cells1");
        cells9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells9ActionPerformed(evt);
            }
        });
        jPanel3.add(cells9);

        cells10.setText("cells1");
        cells10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells10ActionPerformed(evt);
            }
        });
        jPanel3.add(cells10);

        cells11.setText("cells1");
        cells11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells11ActionPerformed(evt);
            }
        });
        jPanel3.add(cells11);

        cells12.setText("cells1");
        cells12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells12ActionPerformed(evt);
            }
        });
        jPanel3.add(cells12);

        cells13.setText("cells1");
        cells13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells13ActionPerformed(evt);
            }
        });
        jPanel3.add(cells13);

        cells14.setText("cells1");
        cells14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells14ActionPerformed(evt);
            }
        });
        jPanel3.add(cells14);

        cells15.setText("cells1");
        cells15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells15ActionPerformed(evt);
            }
        });
        jPanel3.add(cells15);

        cells16.setText("cells1");
        cells16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells16ActionPerformed(evt);
            }
        });
        jPanel3.add(cells16);

        cells17.setText("cells1");
        cells17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells17ActionPerformed(evt);
            }
        });
        jPanel3.add(cells17);

        cells18.setText("cells1");
        cells18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells18ActionPerformed(evt);
            }
        });
        jPanel3.add(cells18);

        cells19.setText("cells1");
        cells19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells19ActionPerformed(evt);
            }
        });
        jPanel3.add(cells19);

        cells20.setText("cells1");
        cells20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells20ActionPerformed(evt);
            }
        });
        jPanel3.add(cells20);

        cells21.setText("cells1");
        cells21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells21ActionPerformed(evt);
            }
        });
        jPanel3.add(cells21);

        cells22.setText("cells1");
        cells22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells22ActionPerformed(evt);
            }
        });
        jPanel3.add(cells22);

        cells23.setText("cells1");
        cells23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells23ActionPerformed(evt);
            }
        });
        jPanel3.add(cells23);

        cells24.setText("cells1");
        cells24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells24ActionPerformed(evt);
            }
        });
        jPanel3.add(cells24);

        cells25.setText("cells1");
        cells25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells25ActionPerformed(evt);
            }
        });
        jPanel3.add(cells25);

        cells26.setText("cells1");
        cells26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells26ActionPerformed(evt);
            }
        });
        jPanel3.add(cells26);

        cells27.setText("cells1");
        cells27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells27ActionPerformed(evt);
            }
        });
        jPanel3.add(cells27);

        cells28.setText("cells1");
        cells28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells28ActionPerformed(evt);
            }
        });
        jPanel3.add(cells28);

        cells29.setText("cells1");
        cells29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells29ActionPerformed(evt);
            }
        });
        jPanel3.add(cells29);

        cells30.setText("cells1");
        cells30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells30ActionPerformed(evt);
            }
        });
        jPanel3.add(cells30);

        cells31.setText("cells1");
        cells31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells31ActionPerformed(evt);
            }
        });
        jPanel3.add(cells31);

        cells32.setText("cells1");
        cells32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells32ActionPerformed(evt);
            }
        });
        jPanel3.add(cells32);

        cells33.setText("cells1");
        cells33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells33ActionPerformed(evt);
            }
        });
        jPanel3.add(cells33);

        cells34.setText("cells1");
        cells34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells34ActionPerformed(evt);
            }
        });
        jPanel3.add(cells34);

        cells35.setText("cells1");
        cells35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells35ActionPerformed(evt);
            }
        });
        jPanel3.add(cells35);

        cells36.setText("cells1");
        cells36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells36ActionPerformed(evt);
            }
        });
        jPanel3.add(cells36);

        cells37.setText("cells1");
        cells37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells37ActionPerformed(evt);
            }
        });
        jPanel3.add(cells37);

        cells38.setText("cells1");
        cells38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells38ActionPerformed(evt);
            }
        });
        jPanel3.add(cells38);

        cells39.setText("cells1");
        cells39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells39ActionPerformed(evt);
            }
        });
        jPanel3.add(cells39);

        cells40.setText("cells1");
        cells40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells40ActionPerformed(evt);
            }
        });
        jPanel3.add(cells40);

        cells41.setText("cells1");
        cells41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells41ActionPerformed(evt);
            }
        });
        jPanel3.add(cells41);

        cells42.setText("cells1");
        cells42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells42ActionPerformed(evt);
            }
        });
        jPanel3.add(cells42);

        cells43.setText("cells1");
        cells43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells43ActionPerformed(evt);
            }
        });
        jPanel3.add(cells43);

        cells44.setText("cells1");
        cells44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells44ActionPerformed(evt);
            }
        });
        jPanel3.add(cells44);

        cells45.setText("cells1");
        cells45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells45ActionPerformed(evt);
            }
        });
        jPanel3.add(cells45);

        cells46.setText("cells1");
        cells46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells46ActionPerformed(evt);
            }
        });
        jPanel3.add(cells46);

        cells47.setText("cells1");
        cells47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells47ActionPerformed(evt);
            }
        });
        jPanel3.add(cells47);

        cells48.setText("cells1");
        cells48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells48ActionPerformed(evt);
            }
        });
        jPanel3.add(cells48);

        cells49.setText("cells1");
        cells49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cells49ActionPerformed(evt);
            }
        });
        jPanel3.add(cells49);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(825, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel3)
                    .addContainerGap(614, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(409, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void cells1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells1ActionPerformed

    private void cells6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells6ActionPerformed

    private void cells7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells7ActionPerformed

    private void cells8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells8ActionPerformed

    private void cells9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells9ActionPerformed

    private void cells10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells10ActionPerformed

    private void cells11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells11ActionPerformed

    private void cells12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells12ActionPerformed

    private void cells13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells13ActionPerformed

    private void cells14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells14ActionPerformed

    private void cells15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells15ActionPerformed

    private void cells16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells16ActionPerformed

    private void cells17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells17ActionPerformed

    private void cells18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells18ActionPerformed

    private void cells19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells19ActionPerformed

    private void cells20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells20ActionPerformed

    private void cells21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells21ActionPerformed

    private void cells22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells22ActionPerformed

    private void cells23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells23ActionPerformed

    private void cells24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells24ActionPerformed

    private void cells25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells25ActionPerformed

    private void cells26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells26ActionPerformed

    private void cells27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells27ActionPerformed

    private void cells28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells28ActionPerformed

    private void cells29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells29ActionPerformed

    private void cells30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells30ActionPerformed

    private void cells31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells31ActionPerformed

    private void cells32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells32ActionPerformed

    private void cells33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells33ActionPerformed

    private void cells34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells34ActionPerformed

    private void cells35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells35ActionPerformed

    private void cells36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells36ActionPerformed

    private void cells37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells37ActionPerformed

    private void cells38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells38ActionPerformed

    private void cells39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells39ActionPerformed

    private void cells40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells40ActionPerformed

    private void cells41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells41ActionPerformed

    private void cells42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells42ActionPerformed

    private void cells43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells43ActionPerformed

    private void cells44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells44ActionPerformed

    private void cells45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells45ActionPerformed

    private void cells46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells46ActionPerformed

    private void cells47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells47ActionPerformed

    private void cells48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells48ActionPerformed

    private void cells49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cells49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cells49ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(swing_calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(swing_calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(swing_calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(swing_calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new swing_calendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Cells cells1;
    private Cells cells10;
    private Cells cells11;
    private Cells cells12;
    private Cells cells13;
    private Cells cells14;
    private Cells cells15;
    private Cells cells16;
    private Cells cells17;
    private Cells cells18;
    private Cells cells19;
    private Cells cells2;
    private Cells cells20;
    private Cells cells21;
    private Cells cells22;
    private Cells cells23;
    private Cells cells24;
    private Cells cells25;
    private Cells cells26;
    private Cells cells27;
    private Cells cells28;
    private Cells cells29;
    private Cells cells3;
    private Cells cells30;
    private Cells cells31;
    private Cells cells32;
    private Cells cells33;
    private Cells cells34;
    private Cells cells35;
    private Cells cells36;
    private Cells cells37;
    private Cells cells38;
    private Cells cells39;
    private Cells cells4;
    private Cells cells40;
    private Cells cells41;
    private Cells cells42;
    private Cells cells43;
    private Cells cells44;
    private Cells cells45;
    private Cells cells46;
    private Cells cells47;
    private Cells cells48;
    private Cells cells49;
    private Cells cells5;
    private Cells cells6;
    private Cells cells7;
    private Cells cells8;
    private Cells cells9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
